### ISSUE TITLE
Create Action that compiles the checklists and posts the result onto PRs

### ISSUE THREAD

**Issue by jrvanwhy** [OpenCorvallis/osfc-checklists#3]
I think it should be possible to create a GitHub action that automatically compiles the checklists in PRs and posts the result (SVG?) as a comment on the PR. Preferably if the PR is updated, it will update the comment.

**Comment by jrvanwhy** [comment]
Looks like GitHub doesn't want people automatically posting comments with embedded images for anti-abuse reasons: https://github.com/cli/cli/issues/1895#issuecomment-1192890735.

I don't think we want to deal with uploading images to an external S3/GCS bucket, but maybe we can do one of the following:

1. Upload an artifact and refer to that.
2. Create a new commit with the images and refer to that.

**Comment by jrvanwhy** [comment]
I thought that uploading an artifact was the way to go, but it turns out artifacts are always uploaded as .zip files, so we can't refer to them from comments.

I'll try storing them in the repository next.

**Comment by jrvanwhy** [comment]
Storing them in the repository seems to work! I have an action that is working in my fork, which I can send after #2 and #4 are merged.

**Comment by andrewda** [comment]
Closing via https://github.com/OpenCorvallis/osfc-checklists/pull/6
